
services:
  apigateway:
    build:
      context: ./api-gateway
    container_name: apigateway
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - customer-service
      - sales-tracking-service
    networks:
      - gateway-network
    restart: unless-stopped
    volumes:
      - ./api-gateway:/usr/src/app
      - ./api-gateway/node_modules:/usr/src/app/node_modules

  sales-tracking-service:
    build:
      context: ./sales-tracking-service
    container_name: sales-tracking-service
    environment:
      - DATABASE_HOST=sales-tracking-service-db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=salesTrackingServiceDb
    depends_on:
      sales-tracking-service-db:
        condition: service_healthy
    networks:
      - sales-tracking-service-db-network
      - gateway-network
    restart: unless-stopped
    volumes:
      - ./sales-tracking-service:/usr/src/app
      - ./sales-tracking-service/node_modules:/usr/src/app/node_modules

  sales-tracking-service-db:
    image: mysql:8
    container_name: sales-tracking-service-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salesTrackingServiceDb
    volumes:
      - sales-tracking-service-db-data:/var/lib/mysql
    ports:
    # test için açık
      - "3308:3306" 
    networks:
      - sales-tracking-service-db-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    environment:
      - DATABASE_HOST=user-db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=userdb
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - user-db-network
      - gateway-network
    restart: unless-stopped
    volumes:
      - ./user-service:/usr/src/app
      - ./user-service/node_modules:/usr/src/app/node_modules

  user-db:
    image: mysql:8
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    volumes:
      - user-db-data:/var/lib/mysql
    ports:
    # test için açık
      - "3307:3306"
    networks:
      - user-db-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  customer-service:
    build:
      context: ./customer-service
    container_name: customer-service
    environment:
      - DATABASE_HOST=customer-db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=customerdb
    depends_on:
      customer-db:
        condition: service_healthy
    networks:
      - customer-db-network
      - gateway-network
    restart: unless-stopped
    volumes:
      - ./customer-service:/usr/src/app
      - ./customer-service/node_modules:/usr/src/app/node_modules

  customer-db:
    image: mysql:8
    container_name: customer-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customerdb
    volumes:
      - customer-db-data:/var/lib/mysql
    ports:
    # test için açık
      - "3309:3306"
    networks:
      - customer-db-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  user-db-network:
    driver: bridge
  customer-db-network:
    driver: bridge
  gateway-network:
    driver: bridge
  sales-tracking-service-db-network:
    driver: bridge

volumes:
  apigateway:
  user-service:
  customer-service:
  sales-tracking-service:
  user-db-data:
  customer-db-data:
  sales-tracking-service-db-data:
